site_name: Surf Accompanist

# Repository
repo_name: 'Surf Accompanist'
repo_url: 'https://github.com/surfstudio/surf-accompanist'

# Navigation
nav:
  - 'Overview': index.md
  - 'DotsNumbers': DotsNumbers.md
  - 'ClickableTextColorAnimation': ClickableTextColorAnimation.md
  - 'MainScaffoldSearch': MainScaffoldSearch.md
  - 'SwipeRefreshList': SwipeRefreshList.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'