site_name: Surf Accompanist

# Navigation
nav:
  - 'Overview': index.md
  - 'MainScaffoldSearch': MainScaffoldSearch.md
  - 'SwipeRefreshList': SwipeRefreshList.md
  - 'ClickableTextColorAnimation': ClickableTextColorAnimation.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'