site_name: KeyGenQt Accompanist

# Repository
repo_name: 'KeyGenQt Accompanist'
repo_url: 'https://github.com/keygenqt/keygenqt-accompanist'

# Navigation
nav:
  - 'Overview': index.md
  - 'SwipeRefreshList': SwipeRefreshList.md
  - 'ClickableTextColorAnimation': ClickableTextColorAnimation.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'